apiVersion: apps/v1
kind: Deployment
metadata:
  name: wulims
  namespace: wulims
spec:
  template:
    spec:
      containers:
        - name: wulims
          image: ghcr.io/walsh-university/wulims@sha256:5f5c9707b3bf3a1a3170b8a644512ac6c56d0f68a15e307291677f30dd3e3955
