apiVersion: apps/v1
kind: Deployment
metadata:
  name: wulims
  namespace: wulims
spec:
  template:
    spec:
      containers:
        - name: wulims
          image: ghcr.io/walsh-university/wulims@sha256:71a8e5ee83be26dc5d11512a86aa0e3aa03bc0f7377cd07e4d6215c3071d692e
