apiVersion: apps/v1
kind: Deployment
metadata:
  name: wulims
  namespace: wulims
spec:
  template:
    spec:
      containers:
        - name: wulims
          image: ghcr.io/walsh-university/wulims@sha256:707306659b9047d49e1077fa543096d408a59532b6649c68d5b3030be9e071fa
