apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: wulims-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - secrets/wulims-db-app.enc.yaml
  - secrets/wulims-secrets.enc.yaml
  - secrets/wulims-db-superuser.enc.yaml
