apiVersion: v1
kind: Secret
metadata:
    name: wulims-secrets
    namespace: wulims
    annotations:
        argocd.argoproj.io/sync-wave: "20"
type: Opaque
stringData:
    DJANGO_SECRET_KEY: ENC[AES256_GCM,data:x2XLmPth5v0t291sfMAUXxog3ik8nOTzX/ROKCLc,iv:QjLCLYHxIODgKX2oH5qjwkOvkgRCLXTelHgBspoS4/s=,tag:3FH8jEbby5eV9zZk+YI2Hg==,type:str]
    DJANGO_ALLOWED_HOSTS: ENC[AES256_GCM,data:SLKru5E1gGcRyeu1U0v+WyE98V+5PqVsUFYWoUA=,iv:Dwz4AaL/Kz7Y0dHbtpBNfuAt47C+E0YiOHyv7GJqwuE=,tag:pBw1eozUUr1RqZeirCyoJw==,type:str]
    DJANGO_DEBUG: ENC[AES256_GCM,data:lg==,iv:Z1i8dRmRjXOdB6vU739zrrfD9At8+SiqWC+jetHBDKM=,tag:P46bZdLJAARC9wKd4eeT6A==,type:str]
    DJANGO_SUPERUSER_USERNAME: ENC[AES256_GCM,data:a6j8KTc=,iv:CctwCiFBmAFsKylIiiJy3DiyKS/CMw11YMMuHUhmFwM=,tag:o8Fy644dtoBWg6Pop9TBZw==,type:str]
    DJANGO_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:iwP4P5wWvZo0qAQBcGWML9ytpUKsd4wp+xbLJ+sN,iv:Wtd/IRrz92WE1vcTOBQFMth2zVAf1JTj6QjVWaxDBdA=,tag:3GFNCggnZd/RN9ZAnwXToQ==,type:str]
    DJANGO_SUPERUSER_EMAIL: ENC[AES256_GCM,data:wdr8cpklwfHpoLE74F27,iv:DcxyT4JKA0FQzpuSOKh6xYwtYFc3Cwl+RTKb7pqF324=,tag:XFSNJ+bHXcHoUmSUQyN1HQ==,type:str]
sops:
    age:
        - recipient: age14xrvg6xm9j2mwkcd3p0fqh6690kcelmz0cgmgup8npyaml0pr50s2xljdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLellXWkRtTnpvaUhBdXZM
            K3JJUmJLdDNncVR4azRUd3pRU2JiWTBPZzNzCnBTdTN2SkNNSCtZMjVueDNXYndy
            Z3BSM2VvRUN6Q1BhZS9VY09yUFJmWXcKLS0tIElLR0ZJS2wyWnRabDRsN3FUMHFu
            aEszZVhRT09nMXhCTG85aDlCTE0ycDgKENlVzo0of6a5oAE+jIwbRfLwzsViXeP9
            SMoNzT2oDbKjU468w91A2z+u8oJJHEqgV9mjRXkJT3Uoeo+xkaA4LA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T19:36:17Z"
    mac: ENC[AES256_GCM,data:PVDJkaboH1yw7F3VTDhCooqU82FIjE2FgWTxJCt6mK8230SAsC8HMNTCFpG8VzSl1rWdEWRCNah4bTvB+6WSUG+HusgDTPhBTsjsJHyMvgsPD/t3vG2GW0c8iTJyPpiIpkAIP5iNPgGKY1MPgPkGiOsuylD9dSQ7KAVsedZNK1k=,iv:wY2zWdcfNvXI+po3R/uhWToGC2jg9cnmSUYV4SXej6U=,tag:WSqwvVqIazjsyAULwMD4Dg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
