apiVersion: v1
kind: Secret
metadata:
    name: wulims-db-superuser
    namespace: wulims
    annotations:
        argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:pGG543CpT4M=,iv:CAC2pCLSi3xSNyZbMiVxnDKxD+pYPwSfeUp2Qy9hZsU=,tag:JW/BRYfeC15rfKu/xkDrjg==,type:str]
    password: ENC[AES256_GCM,data:sVwgq+urHm5fD0CLzhEFoYTlxb57/tPneTuqJaLU,iv:A0z2KVca+z8uGmPYN043qFktDi2M+CjFK8kPRiWsfeY=,tag:v9Zvq2KkfM8dXH35eRAA3A==,type:str]
sops:
    age:
        - recipient: age14xrvg6xm9j2mwkcd3p0fqh6690kcelmz0cgmgup8npyaml0pr50s2xljdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoS2NCWGFkQlNXZVpYc1dy
            WVNzUHZ5OHdyL2NBeU84ZWhTTEVaa1V3UWdVCkhPUit3VHd5Y1RtbHRyemhwU0x3
            dHlrMm53OGlRczhGdGUrTEsyN0g1TXMKLS0tIFlBK3NkWmJib0dPcDBuSmYvQjJs
            UFNmSzNxT2doRm9FMFgzaUNLd3BkOHMKzzaKBr++Cpff3sYvzIUD+0lPqduOqloE
            Iv7Y4i4Bg14WcItSVUtkXlIooMLw3oC1Si72qMVBsjVRVrxuM6xHdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T03:03:16Z"
    mac: ENC[AES256_GCM,data:IdiWk6u+x7NWRDwptkRxy+DeDp007/LEDW2dPzU0XKSQxPkPVW35pbZOrQSU2ZNm1emMKB/ZlJGvn78SccAquDJfY+YovttFiJWTDpNhVYgJiXA+GoRQInx6wSc/uGthxE8HpVW6S0hL4hyp/d3f0r/9smYRcKu08A0v9CaD1fY=,iv:s7DZmFei6U/cF7dhEgVz0lzECQi/bB9wi5sxpdVyjb4=,tag:jphEzRJ2xp8OpsEpNO4GuA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
