apiVersion: v1
kind: Secret
metadata:
    name: wulims-secrets
    namespace: wulims
    annotations:
        argocd.argoproj.io/sync-wave: "20"
type: Opaque
stringData:
    DJANGO_SECRET_KEY: ENC[AES256_GCM,data:K3LKZ/YnjHxfv7Z50a5N1lcSMUH0nGcWNDyU1CwH,iv:5qu7NSJA6luWSzBigPDTOsv5jB6tW54Mfo8xGzXW9J0=,tag:rnNWDkauYAPJFMc1J2uIoQ==,type:str]
    DJANGO_DEBUG: ENC[AES256_GCM,data:0A==,iv:B1OUJ4gqE2dAsnox6Qb4N1mHYSRSbTtQpBFQ62+S3Uk=,tag:8k+YjAV4GZyru60ysBC3HQ==,type:str]
    DJANGO_SUPERUSER_USERNAME: ENC[AES256_GCM,data:0m9CcXk=,iv:fEnBIfQHlnzrwbbb7sw8EIuOChUHxURAO02wlvvcuR4=,tag:Y60KhDcWby5MGu1lc1+Qnw==,type:str]
    DJANGO_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:rop61IcEVlmZ5ty5+N3VdIbH7JJgQdd8/jAFXSHe,iv:g7qjTUy1BLOUxAPbT/A7cAYkgoqfI6d8NDfderXAZZM=,tag:Lnmh2pFrsTd5eXL7H7FMGQ==,type:str]
    DJANGO_SUPERUSER_EMAIL: ENC[AES256_GCM,data:kOD6hxZXZ8VA7FKSH9Bf,iv:+xsOX6GQdsHUa3xXNx4tLZs8EuGNfbpg8igovGSPfFk=,tag:a61Qd7hpIq0zpYCPw23M5g==,type:str]
sops:
    age:
        - recipient: age14xrvg6xm9j2mwkcd3p0fqh6690kcelmz0cgmgup8npyaml0pr50s2xljdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBreitSZW5mV2hnZjU4NFI5
            TWUybE5pSm5Md1pCRktHSjl5M1RhWEl1YTFRCnBWZGF0aUU5M2RBQzl6dHdHME9w
            OXc0UXhGVU1HcFgvaEdhZXBtQ1Q2M0EKLS0tIHd4aTRTVE9jVEJiQlh4ZU5ndEF5
            d2pZZHlEeDNMSFRWVG5id242Z1dsSHcKwETm5twd2blwIfBDm5DmbJGCafp4irIo
            MqG3Kzn8Co6+lkPpugqQoag8ZZTWrMzvm1JJbIXGIt463Jh7diR4mA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T21:57:20Z"
    mac: ENC[AES256_GCM,data:oL4kz6GJXxI2Dg/VWeKHlX0brIDPsdnufSuUtbaR1nF+PhjofkIKijRai/QhU666wgEdv/3PRvhqM2xF7HCLpEei/YqgiRXdu5OSog2jeb6K2OnVq3oEQopJdnmedfSs4pWSJGQfcEhwPw0lacXy5jZhMqqghR04OSx5FJeVrxU=,iv:RfNf09Xaj+V3lYg9owmQ0dxaPtpSfvGcw39UtzSVj54=,tag:qcX0fWg1CQuohtJ+Btr1dA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
