apiVersion: v1
kind: Secret
metadata:
    name: wulims-secrets
    namespace: wulims
    annotations:
        argocd.argoproj.io/sync-wave: "20"
type: Opaque
stringData:
    DJANGO_SECRET_KEY: ENC[AES256_GCM,data:k72lrXbwNz3PrPrz2xQFRJ1AqViG7juIjOMvjKWx,iv:dyoU4QgFRmUl4+SZGjA7kCiS+PLTgsnA79cnyJv2Ixk=,tag:P6R1qhwOfRBMd6mzQPwmKQ==,type:str]
    DJANGO_ALLOWED_HOSTS: ENC[AES256_GCM,data:A0uNkXX8ISCmg3RUc4dXZUJ0/vzwf1D7S+/B/7o=,iv:/nvr7oDT4+VDlNKdEeTAMFQBMeyVRi7+tla93iB9yao=,tag:UtFD195jtAKVw+5gHplyFw==,type:str]
    DJANGO_DEBUG: ENC[AES256_GCM,data:zQ==,iv:aKxkIWGZgIIBu1GajPDWYFwBrZMtFjn1uoD4ObTIweU=,tag:WSJN0Zfqv9KhqmOyw5J29w==,type:str]
    #ENC[AES256_GCM,data:SdJeIHyA/Z2Z7alitwtTCdpDVWZZFltpiNzMg1HYugslqMS5,iv:vgH+enjMPldC3dmu5gB4GX7NlVoSQtn8Nja8oanWnHQ=,tag:T7v3yD4vAvl0N/PMNFfPgQ==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:p6AvcCMYOfkKRL50tGEDfh146TMP1fz38az0Mh1/IdrcNkmOe9z12EQk6u9x2MMfu9HGtpjVSeqwgYCULnZK87TnQjiOipvTMJQ7dqXjQGXb3FZFxRns6HCQ5LknqOSU/SNy6A==,iv:8AmHjbfw+FHo4OZWlO6rTczvTgVuzorUSB2lBr8gyQg=,tag:mlp1zrJ/w7pkaWjTyKkbqg==,type:str]
    DJANGO_SUPERUSER_USERNAME: ENC[AES256_GCM,data:F463Akc=,iv:H80XDLAK6X+sx11fjZ219Fr3aF0H8I/fqPIesNo72DI=,tag:DNfx2v8dVy948+kv//zUHQ==,type:str]
    DJANGO_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:kVTynLiz/K3/0kBtDKW8dOg/psi97m2BqJpBT33W,iv:3RoPI/x46eVHqd8fktYMoGO/xqpmWnK+UGt5lBgbcUw=,tag:Qnz2V63mGmZNlyJvOLCsAA==,type:str]
    DJANGO_SUPERUSER_EMAIL: ENC[AES256_GCM,data:+Fv032b3fw6EX71WETZa,iv:NFuphdDMTVL5ryGo9x/bCxaIs5a7K2JDUeH7+xWxdOc=,tag:OQvIJZ/RSy3nYKR/1W/bWg==,type:str]
sops:
    age:
        - recipient: age14xrvg6xm9j2mwkcd3p0fqh6690kcelmz0cgmgup8npyaml0pr50s2xljdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcmhOSlZZdmdUWStZWmlP
            cFpobkw2OFFzR1hzaGJ2M2Uxc3NOVi9FemxNClF2UkVXVzJsM3gxcndwQzdtcFNT
            YnI0QkNvSExrRTRmVE55U0xYbVRRa3cKLS0tIEpLTWNPbmhhZXkrRlNUYzAyeVlq
            cHhnWlBETWp3MldxUTFRbWN2dUplS0EKpe3H1YStkns77aExGy15LNnq4KPQJBWM
            pJUfelxkx8ynHxHFqoXKTgAnL8m6Yhs8WB20+JgHDOu7NENMlmjgig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T18:17:26Z"
    mac: ENC[AES256_GCM,data:0VTsolJYcRCoCgfRR01bhb9/TLx1o+8JjeINj1LSWZUQ8E7i8aBaAO7ZDT0gihMNY2bpaNi0f8FnXEQ3gqPPtT00r3Uycf7GpzRDdDwID4TdfoLL7aahMYwKW/m066VL5wi2IMg8PBAWoGmPmp7ODbSQIg2F4PxerMgsh243ZAE=,iv:QKSUJRbYPsFD4img8sR37MjYbtBjgGLuGmW+raOvsP0=,tag:C/6ua0Q35z4HZjfVYf4Gvw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
