apiVersion: v1
kind: Secret
metadata:
    name: wulims-db-app
    namespace: wulims
    annotations:
        argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:I/U/nU9C,iv:1hyEsAL8Kma0f2vopaoVvaIPMOFfzy7Lfs2gtaxubdc=,tag:jXeTeF3v2XzZYD20GnRRTg==,type:str]
    password: ENC[AES256_GCM,data:PxIYDe1rzaHE8lBrnsNqP9KE0Ll4oeDwCg+lHDUr,iv:eEbzNjgKZW4W5GAHuW5HeX1KM4XWb5tmmswTQskajwI=,tag:Sbe46/BJ8fLj/ajeoD73tQ==,type:str]
sops:
    age:
        - recipient: age14xrvg6xm9j2mwkcd3p0fqh6690kcelmz0cgmgup8npyaml0pr50s2xljdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbzlQQ0VET3dYV0FhNkJt
            TUovaEpaL2U3WFgzSkgyNGZWb2lKbGxnekRvCjVGR3ZKRUo0R2VIa0dvY3JJajlO
            U1lsSHpFaGcyeDRpUHAvUzJDM3lzOGMKLS0tIEYyLzR2L042SXV3eUZkeDZCYW40
            ZnpoVHplT3VVMmJUdnRiQTFQRDZub28KcL2iJrPuGfi4WeKGBBlbQOQ9WCm9+eD/
            FNBHWbKa0LmkEwGcL7IqU/SpNN9hWw7jGJRW1lkryOLOJwSrTihwLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T03:02:39Z"
    mac: ENC[AES256_GCM,data:ckiOXb9ryW2/jFR1MSNHiT2KdQ8/G5nQHf1w3nqnAkOG+HxWq7C40+JUbBj1/Cqverccx2HX7bp0Z3kUu75B5QHwON9oYhBaba1V4DkB5GFDKhjc/hQwfv04HnlxsKuafDcWndYHa6Al/i90/GoyjLaxD0pszMr3nNLE1fNqs1o=,iv:d7q1gqDMtNffl6JJnMsBHvGkjGFCtRngdBwQGHxpzJI=,tag:a6HcC+sVtd6DBLLjKLdQNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
