apiVersion: apps/v1
kind: Deployment
metadata:
  name: wulims
  namespace: wulims
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wulims
  template:
    metadata:
      labels:
        app: wulims
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: wulims
          image: ghcr.io/walsh-university/wulims:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
          - name: DJANGO_SETTINGS_MODULE
            value: config.settings.prod
          - name: DB_NAME
            value: wulims
          - name: DB_HOST
            value: wulims-pg-rw.wulims.svc.cluster.local
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: wulims-db-app
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wulims-db-app
                key: password
          envFrom:
            - configMapRef:
                name: wulims-config
            - secretRef:
                name: wulims-secrets
          readinessProbe:
            httpGet:
              path: /healthz/
              port: 8000
              host: wulims.wulims.svc.cluster.local
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /healthz/
              port: 8000
              host: wulims.wulims.svc.cluster.local
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
